### ISSUE TITLE
Better way to handle No nodes to query error?

### ISSUE THREAD

**Issue by draeder** [mafintosh/k-rpc#20]
I'm using [bittorrent-dht](https://github.com/webtorrent/bittorrent-dht) to put and get arbitrary data on the DHT. 

K-RPC is generating this error despite successful puts & gets. I've tried to suppress this error in my code but it looks like line 127 has it hard coded. Could you simply quietly `return`?

```js
if (!missing) return cb(new Error('No nodes to query'), 0)
```

```js
Error: No nodes to query
    at RPC.queryAll (/Users/danraeder/Documents/GitHub/dht-keyvalue/node_modules/k-rpc/index.js:127:27)
    at DHT._put (/Users/danraeder/Documents/GitHub/dht-keyvalue/node_modules/bittorrent-dht/client.js:318:15)
    at DHT.put (/Users/danraeder/Documents/GitHub/dht-keyvalue/node_modules/bittorrent-dht/client.js:283:17)
    at /Users/danraeder/Documents/GitHub/dht-keyvalue/node_modules/bittorrent-dht/client.js:337:12
    at done (/Users/danraeder/Documents/GitHub/dht-keyvalue/node_modules/bittorrent-dht/client.js:677:7)
    at done (/Users/danraeder/Documents/GitHub/dht-keyvalue/node_modules/k-rpc/index.js:248:5)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Comment by draeder** [comment]
Nevermind.. I missed a `console.log(err)` in my example.js code
